version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7.0
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami/zookeeper"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    mem_limit: 1000mb
  kafka:
    image: docker.io/bitnami/kafka:3.1.0
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami/kafka"
    environment:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    mem_limit: 1000mb
    depends_on:
      - zookeeper
  spark:
    image: docker.io/bitnami/spark:3.2.1
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - "spark_data:/bitnami/spark"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    mem_limit: 1000mb
  spark-worker:
    image: docker.io/bitnami/spark:3.2.1
    ports:
      - "8081:8081"
    volumes:
      - "spark_data:/bitnami/spark-worker"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    mem_limit: 2000mb
  cassandra:
    image: docker.io/cassandra:4.0.3
    ports:
      - "7000:7000"
      - "9042:9042"
    volumes:
      - "cassandra_data:/bitnami/cassandra"
    environment:
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
  solr:
    image: docker.io/bitnami/solr:8.11.1
    ports:
      - "8983:8983"
    volumes:
      - "solr_data:/bitnami/solr"
    environment:
      - SOLR_ENABLE_AUTHENTICATION=no
    mem_limit: 1000mb
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  spark_data:
    driver: local
  cassandra_data:
    driver: local
  solr_data:
    driver: local