version: "2"

services:
  cassandra:
    image: docker.io/cassandra:4.0.3
    ports:
      - "7000:7000"
      - "9042:9042"
    volumes:
      - "cassandra_data:/bitnami/cassandra"
    environment:
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
volumes:
  cassandra_data:
    driver: local
